export const Countries = [
    { code: 'AF', name: 'Afghanistan', id: 'c32', phoneCode: 'Afghanistan (+93)' },
    { code: 'AL', name: 'Albania', id: 'c33', phoneCode: 'Albania (+355)' },
    { code: 'DZ', name: 'Algeria', id: 'c34', phoneCode: 'Algeria (+213)' },
    { code: 'AS', name: 'American Samoa', id: 'c35', phoneCode: 'American Samoa (+1-684)' },
    { code: 'AD', name: 'Andorra', id: 'c36', phoneCode: 'Andorra (+376)' },
    { code: 'AO', name: 'Angola', id: 'c37', phoneCode: 'Angola (+244)' },
    { code: 'AI', name: 'Anguilla', id: 'c38', phoneCode: 'Anguilla (+1-264)' },
    { code: 'AG', name: 'Antigua and Barbuda', id: 'c39', phoneCode: 'Antigua and Barbuda (+1-268)' },
    { code: 'AR', name: 'Argentina', id: 'c40', phoneCode: 'Argentina (+54)' },
    { code: 'AM', name: 'Armenia', id: 'c41', phoneCode: 'Armenia (+374)' },
    { code: 'AW', name: 'Aruba', id: 'c42', phoneCode: 'Aruba (+297)' },
    { code: 'AU', name: 'Australia', id: 'c43', phoneCode: 'Australia (+61)' },
    { code: 'AT', name: 'Austria', id: 'c44', phoneCode: 'Austria (+43)' },
    { code: 'AZ', name: 'Azerbaijan', id: 'c45', phoneCode: 'Azerbaijan (+994)' },
    { code: 'BS', name: 'Bahamas', id: 'c46', phoneCode: 'Bahamas (+1-242)' },
    { code: 'BH', name: 'Bahrain', id: 'c47', phoneCode: 'Bahrain (+973)' },
    { code: 'BD', name: 'Bangladesh', id: 'c48', phoneCode: 'Bangladesh (+880)' },
    { code: 'BB', name: 'Barbados', id: 'c49', phoneCode: 'Barbados (+1-246)' },
    { code: 'BY', name: 'Belarus', id: 'c50', phoneCode: 'Belarus (+375)' },
    { code: 'BE', name: 'Belgium', id: 'c51', phoneCode: 'Belgium (+32)' },
    { code: 'BZ', name: 'Belize', id: 'c52', phoneCode: 'Belize (+501)' },
    { code: 'BJ', name: 'Benin', id: 'c53', phoneCode: 'Benin (+229)' },
    { code: 'BM', name: 'Bermuda', id: 'c54', phoneCode: 'Bermuda (+1-441)' },
    { code: 'BT', name: 'Bhutan', id: 'c55', phoneCode: 'Bhutan (+975)' },
    { code: 'BO', name: 'Bolivia', id: 'c56', phoneCode: 'Bolivia (+591)' },
    { code: 'BA', name: 'Bosnia and Herzegovina', id: 'c57', phoneCode: 'Bosnia and Herzegovina (+387)' },
    { code: 'BW', name: 'Botswana', id: 'c58', phoneCode: 'Botswana (+267)' },
    { code: 'BR', name: 'Brazil', id: 'c59', phoneCode: 'Brazil (+55)' },
    { code: 'IO', name: 'British Indian Ocean Territory', id: 'c60', phoneCode: 'British Indian Ocean Territory (+246)' },
    { code: '', name: 'British Virgin Islands', id: 'c61', phoneCode: 'British Virgin Islands (+1-284)' },
    { code: 'BN', name: 'Brunei', id: 'c62', phoneCode: 'Brunei (+673)' },
    { code: 'BG', name: 'Bulgaria', id: 'c63', phoneCode: 'Bulgaria (+359)' },
    { code: 'BF', name: 'Burkina Faso', id: 'c64', phoneCode: 'Burkina Faso (+226)' },
    { code: 'BI', name: 'Burundi', id: 'c65', phoneCode: 'Burundi (+257)' },
    { code: 'KH', name: 'Cambodia', id: 'c66', phoneCode: 'Cambodia (+855)' },
    { code: 'CM', name: 'Cameroon', id: 'c67', phoneCode: 'Cameroon (+237)' },
    { code: 'CA', name: 'Canada', id: 'c68', phoneCode: 'Canada (+1)' },
    { code: 'CV', name: 'Cape Verde', id: 'c69', phoneCode: 'Cape Verde (+238)' },
    { code: 'KY', name: 'Cayman Islands', id: 'c70', phoneCode: 'Cayman Islands (+1-345)' },
    { code: 'CF', name: 'Central African Republic', id: 'c71', phoneCode: 'Central African Republic (+236)' },
    { code: 'TD', name: 'Chad', id: 'c72', phoneCode: 'Chad (+235)' },
    { code: 'CL', name: 'Chile', id: 'c73', phoneCode: 'Chile (+56)' },
    { code: 'CN', name: 'China', id: 'c74', phoneCode: 'China (+86)' },
    { code: '', name: 'Christmas Island', id: 'c75', phoneCode: 'Christmas Island (+61)' },
    { code: '', name: 'Cocos Islands', id: 'c76', phoneCode: 'Cocos Islands (+61)' },
    { code: 'CO', name: 'Colombia', id: 'c77', phoneCode: 'Colombia (+57)' },
    { code: 'KM', name: 'Comoros', id: 'c78', phoneCode: 'Comoros (+269)' },
    { code: 'CK', name: 'Cook Islands', id: 'c79', phoneCode: 'Cook Islands (+682)' },
    { code: 'CR', name: 'Costa Rica', id: 'c80', phoneCode: 'Costa Rica (+506)' },
    { code: 'HR', name: 'Croatia', id: 'c81', phoneCode: 'Croatia (+385)' },
    { code: 'CU', name: 'Cuba', id: 'c82', phoneCode: 'Cuba (+53)' },
    { code: 'CY', name: 'Cyprus', id: 'c83', phoneCode: 'Cyprus (+357)' },
    { code: 'CZ', name: 'Czech Republic', id: 'c84', phoneCode: 'Czech Republic (+420)' },
    { code: 'CD', name: 'Democratic Republic of the Congo', id: 'c85', phoneCode: 'Democratic Republic of the Congo (+243)' },
    { code: 'DK', name: 'Denmark', id: 'c86', phoneCode: 'Denmark (+45)' },
    { code: 'DJ', name: 'Djibouti', id: 'c87', phoneCode: 'Djibouti (+253)' },
    { code: 'DM', name: 'Dominica', id: 'c88', phoneCode: 'Dominica (+1-767)' },
    { code: 'DO', name: 'Dominican Republic', id: 'c89', phoneCode: 'Dominican Republic (+1-809)' },
    { code: 'DO', name: 'Dominican Republic', id: 'c90', phoneCode: 'Dominican Republic (+1-829)' },
    { code: '', name: 'East Timor', id: 'c91', phoneCode: 'East Timor (+670)' },
    { code: 'EC', name: 'Ecuador', id: 'c92', phoneCode: 'Ecuador (+593)' },
    { code: 'EG', name: 'Egypt', id: 'c93', phoneCode: 'Egypt (+20)' },
    { code: 'SV', name: 'El Salvador', id: 'c94', phoneCode: 'El Salvador (+503)' },
    { code: 'GQ', name: 'Equatorial Guinea', id: 'c95', phoneCode: 'Equatorial Guinea (+240)' },
    { code: 'ER', name: 'Eritrea', id: 'c96', phoneCode: 'Eritrea (+291)' },
    { code: 'EE', name: 'Estonia', id: 'c97', phoneCode: 'Estonia (+372)' },
    { code: 'ET', name: 'Ethiopia', id: 'c98', phoneCode: 'Ethiopia (+251)' },
    { code: 'FK', name: 'Falkland Islands', id: 'c99', phoneCode: 'Falkland Islands (+500)' },
    { code: 'FO', name: 'Faroe Islands', id: 'c100', phoneCode: 'Faroe Islands (+298)' },
    { code: 'FJ', name: 'Fiji', id: 'c101', phoneCode: 'Fiji (+679)' },
    { code: 'FI', name: 'Finland', id: 'c102', phoneCode: 'Finland (+358)' },
    { code: 'FR', name: 'France', id: 'c103', phoneCode: 'France (+33)' },
    { code: 'PF', name: 'French Polynesia', id: 'c104', phoneCode: 'French Polynesia (+689)' },
    { code: 'GA', name: 'Gabon', id: 'c105', phoneCode: 'Gabon (+241)' },
    { code: 'GM', name: 'Gambia', id: 'c106', phoneCode: 'Gambia (+220)' },
    { code: 'GE', name: 'Georgia', id: 'c107', phoneCode: 'Georgia (+995)' },
    { code: 'DE', name: 'Germany', id: 'c108', phoneCode: 'Germany (+49)' },
    { code: 'GH', name: 'Ghana', id: 'c109', phoneCode: 'Ghana (+233)' },
    { code: 'GI', name: 'Gibraltar', id: 'c110', phoneCode: 'Gibraltar (+350)' },
    { code: 'GR', name: 'Greece', id: 'c111', phoneCode: 'Greece (+30)' },
    { code: 'GL', name: 'Greenland', id: 'c112', phoneCode: 'Greenland (+299)' },
    { code: 'GD', name: 'Grenada', id: 'c113', phoneCode: 'Grenada (+1-473)' },
    { code: 'GU', name: 'Guam', id: 'c114', phoneCode: 'Guam (+1-671)' },
    { code: 'GT', name: 'Guatemala', id: 'c115', phoneCode: 'Guatemala (+502)' },
    { code: 'GN', name: 'Guinea', id: 'c116', phoneCode: 'Guinea (+224)' },
    { code: 'GN', name: 'Guinea', id: 'c117', phoneCode: 'Guinea (+245)' },
    { code: 'GN', name: 'Guyana', id: 'c118', phoneCode: 'Guyana (+592)' },
    { code: 'HT', name: 'Haiti', id: 'c119', phoneCode: 'Haiti (+509)' },
    { code: 'HN', name: 'Honduras', id: 'c120', phoneCode: 'Honduras (+504)' },
    { code: 'HK', name: 'Hong Kong', id: 'c121', phoneCode: 'Hong Kong (+852)' },
    { code: 'HU', name: 'Hungary', id: 'c122', phoneCode: 'Hungary (+36)' },
    { code: 'IS', name: 'Iceland', id: 'c123', phoneCode: 'Iceland (+354)' },
    { code: 'IN', name: 'India', id: 'c124', phoneCode: 'India (+91)' },
    { code: 'ID', name: 'Indonesia', id: 'c125', phoneCode: 'Indonesia (+62)' },
    { code: 'IR', name: 'Iran', id: 'c126', phoneCode: 'Iran (+98)' },
    { code: 'IQ', name: 'Iraq', id: 'c127', phoneCode: 'Iraq (+964)' },
    { code: 'IE', name: 'Ireland', id: 'c128', phoneCode: 'Ireland (+353)' },
    { code: 'IM', name: 'Isle of Man', id: 'c129', phoneCode: 'Isle of Man (+44-1624)' },
    { code: 'IL', name: 'Israel', id: 'c130', phoneCode: 'Israel (+972)' },
    { code: 'IT', name: 'Italy', id: 'c131', phoneCode: 'Italy (+39)' },
    { code: '', name: 'Ivory Coast', id: 'c132', phoneCode: 'Ivory Coast (+225)' },
    { code: 'JM', name: 'Jamaica', id: 'c133', phoneCode: 'Jamaica (+1-876)' },
    { code: 'JP', name: 'Japan', id: 'c134', phoneCode: 'Japan (+81)' },
    { code: 'JE', name: 'Jersey', id: 'c135', phoneCode: 'Jersey (+44-1534)' },
    { code: 'JO', name: 'Jordan', id: 'c136', phoneCode: 'Jordan (+962)' },
    { code: 'KZ', name: 'Kazakhstan', id: 'c137', phoneCode: 'Kazakhstan (+7)' },
    { code: 'KE', name: 'Kenya', id: 'c138', phoneCode: 'Kenya (+254)' },
    { code: 'KI', name: 'Kiribati', id: 'c139', phoneCode: 'Kiribati (+686)' },
    { code: 'KW', name: 'Kuwait', id: 'c140', phoneCode: 'Kuwait (+965)' },
    { code: 'KG', name: 'Kyrgyzstan', id: 'c141', phoneCode: 'Kyrgyzstan (+996)' },
    { code: 'LA', name: 'Laos', id: 'c142', phoneCode: 'Laos (+856)' },
    { code: 'LV', name: 'Latvia', id: 'c143', phoneCode: 'Latvia (+371)' },
    { code: 'LB', name: 'Lebanon', id: 'c144', phoneCode: 'Lebanon (+961)' },
    { code: 'LS', name: 'Lesotho', id: 'c145', phoneCode: 'Lesotho (+266)' },
    { code: 'LR', name: 'Liberia', id: 'c146', phoneCode: 'Liberia (+231)' },
    { code: 'LY', name: 'Libya', id: 'c147', phoneCode: 'Libya (+218)' },
    { code: 'LI', name: 'Liechtenstein', id: 'c148', phoneCode: 'Liechtenstein (+423)' },
    { code: 'LT', name: 'Lithuania', id: 'c149', phoneCode: 'Lithuania (+370)' },
    { code: 'LU', name: 'Luxembourg', id: 'c150', phoneCode: 'Luxembourg (+352)' },
    { code: 'MO', name: 'Macao', id: 'c151', phoneCode: 'Macao (+853)' },
    { code: 'MK', name: 'Macedonia', id: 'c152', phoneCode: 'Macedonia (+389)' },
    { code: 'MG', name: 'Madagascar', id: 'c153', phoneCode: 'Madagascar (+261)' },
    { code: 'MW', name: 'Malawi', id: 'c154', phoneCode: 'Malawi (+265)' },
    { code: 'MY', name: 'Malaysia', id: 'c155', phoneCode: 'Malaysia (+60)' },
    { code: 'MV', name: 'Maldives', id: 'c156', phoneCode: 'Maldives (+960)' },
    { code: 'ML', name: 'Mali', id: 'c157', phoneCode: 'Mali (+223)' },
    { code: 'MT', name: 'Malta', id: 'c158', phoneCode: 'Malta (+356)' },
    { code: 'MH', name: 'Marshall Islands', id: 'c159', phoneCode: 'Marshall Islands (+692)' },
    { code: 'MQ', name: 'Martinique', id: 'c160', phoneCode: 'Martinique (+596)' },
    { code: 'MR', name: 'Mauritania', id: 'c161', phoneCode: 'Mauritania (+222)' },
    { code: 'MU', name: 'Mauritius', id: 'c162', phoneCode: 'Mauritius (+230)' },
    { code: 'YT', name: 'Mayotte', id: 'c163', phoneCode: 'Mayotte (+262)' },
    { code: 'MX', name: 'Mexico', id: 'c164', phoneCode: 'Mexico (+52)' },
    { code: 'FM', name: 'Micronesia', id: 'c165', phoneCode: 'Micronesia (+691)' },
    { code: 'MD', name: 'Moldova', id: 'c166', phoneCode: 'Moldova (+373)' },
    { code: 'MC', name: 'Monaco', id: 'c167', phoneCode: 'Monaco (+377)' },
    { code: 'MN', name: 'Mongolia', id: 'c168', phoneCode: 'Mongolia (+976)' },
    { code: 'ME', name: 'Montenegro', id: 'c169', phoneCode: 'Montenegro (+382)' },
    { code: 'MS', name: 'Montserrat', id: 'c170', phoneCode: 'Montserrat (+1-664)' },
    { code: 'MA', name: 'Morocco', id: 'c171', phoneCode: 'Morocco (+212)' },
    { code: 'MZ', name: 'Mozambique', id: 'c172', phoneCode: 'Mozambique (+258)' },
    { code: 'MM', name: 'Myanmar', id: 'c173', phoneCode: 'Myanmar (+95)' },
    { code: 'NA', name: 'Namibia', id: 'c174', phoneCode: 'Namibia (+264)' },
    { code: 'NR', name: 'Nauru', id: 'c175', phoneCode: 'Nauru (+674)' },
    { code: 'NP', name: 'Nepal', id: 'c176', phoneCode: 'Nepal (+977)' },
    { code: 'NL', name: 'Netherlands', id: 'c177', phoneCode: 'Netherlands (+31)' },
    { code: '', name: 'Netherlands Antilles', id: 'c178', phoneCode: 'Netherlands Antilles (+599)' },
    { code: 'NC', name: 'New Caledonia', id: 'c179', phoneCode: 'New Caledonia (+687)' },
    { code: 'NZ', name: 'New Zealand', id: 'c180', phoneCode: 'New Zealand (+64)' },
    { code: 'NI', name: 'Nicaragua', id: 'c181', phoneCode: 'Nicaragua (+505)' },
    { code: 'NE', name: 'Niger', id: 'c182', phoneCode: 'Niger (+227)' },
    { code: 'NG', name: 'Nigeria', id: 'c183', phoneCode: 'Nigeria (+234)' },
    { code: 'NU', name: 'Niue', id: 'c184', phoneCode: 'Niue (+683)' },
    { code: '', name: 'North Korea', id: 'c185', phoneCode: 'North Korea (+850)' },
    { code: 'MP', name: 'Northern Mariana Islands', id: 'c186', phoneCode: 'Northern Mariana Islands (+1-670)' },
    { code: 'NO', name: 'Norway', id: 'c187', phoneCode: 'Norway (+47)' },
    { code: 'OM', name: 'Oman', id: 'c188', phoneCode: 'Oman (+968)' },
    { code: 'PK', name: 'Pakistan', id: 'c189', phoneCode: 'Pakistan (+92)' },
    { code: 'PW', name: 'Palau', id: 'c190', phoneCode: 'Palau (+680)' },
    { code: 'PA', name: 'Panama', id: 'c191', phoneCode: 'Panama (+507)' },
    { code: 'PG', name: 'Papua New Guinea', id: 'c192', phoneCode: 'Papua New Guinea (+675)' },
    { code: 'PY', name: 'Paraguay', id: 'c193', phoneCode: 'Paraguay (+595)' },
    { code: 'PE', name: 'Peru', id: 'c194', phoneCode: 'Peru (+51)' },
    { code: 'PH', name: 'Philippines', id: 'c195', phoneCode: 'Philippines (+63)' },
    { code: 'PN', name: 'Pitcairn', id: 'c196', phoneCode: 'Pitcairn (+870)' },
    { code: 'PL', name: 'Poland', id: 'c197', phoneCode: 'Poland (+48)' },
    { code: 'PT', name: 'Portugal', id: 'c198', phoneCode: 'Portugal (+351)' },
    { code: 'PR', name: 'Puerto Rico (+1-787)', id: 'c199', phoneCode: 'Puerto Rico (+1-787) (+1-787)' },
    { code: 'PR', name: 'Puerto Rico (+1-939)', id: 'c200', phoneCode: 'Puerto Rico (+1-939) (+1-939)' },
    { code: 'QA', name: 'Qatar', id: 'c201', phoneCode: 'Qatar (+974)' },
    { code: 'CG', name: 'Republic of the Congo', id: 'c202', phoneCode: 'Republic of the Congo (+242)' },
    { code: 'RO', name: 'Romania', id: 'c203', phoneCode: 'Romania (+40)' },
    { code: 'RU', name: 'Russia', id: 'c204', phoneCode: 'Russia (+7)' },
    { code: 'RW', name: 'Rwanda', id: 'c205', phoneCode: 'Rwanda (+250)' },
    { code: '', name: 'Saint Barthelemy', id: 'c206', phoneCode: 'Saint Barthelemy (+590)' },
    { code: 'SH', name: 'Saint Helena', id: 'c207', phoneCode: 'Saint Helena (+290)' },
    { code: 'KN', name: 'Saint Kitts and Nevis', id: 'c208', phoneCode: 'Saint Kitts and Nevis (+1-869)' },
    { code: 'LC', name: 'Saint Lucia', id: 'c209', phoneCode: 'Saint Lucia (+1-758)' },
    { code: 'MF', name: 'Saint Martin', id: 'c210', phoneCode: 'Saint Martin (+590)' },
    { code: 'PM', name: 'Saint Pierre and Miquelon', id: 'c211', phoneCode: 'Saint Pierre and Miquelon (+508)' },
    { code: 'VC', name: 'Saint Vincent and the Grenadines', id: 'c212', phoneCode: 'Saint Vincent and the Grenadines (+1-784)' },
    { code: 'WS', name: 'Samoa', id: 'c213', phoneCode: 'Samoa (+685)' },
    { code: 'SM', name: 'San Marino', id: 'c214', phoneCode: 'San Marino (+378)' },
    { code: 'ST', name: 'Sao Tome and Principe', id: 'c215', phoneCode: 'Sao Tome and Principe (+239)' },
    { code: 'SA', name: 'Saudi Arabia', id: 'c216', phoneCode: 'Saudi Arabia (+966)' },
    { code: 'SN', name: 'Senegal', id: 'c217', phoneCode: 'Senegal (+221)' },
    { code: 'RS', name: 'Serbia', id: 'c218', phoneCode: 'Serbia (+381)' },
    { code: 'SC', name: 'Seychelles', id: 'c219', phoneCode: 'Seychelles (+248)' },
    { code: 'SL', name: 'Sierra Leone', id: 'c220', phoneCode: 'Sierra Leone (+232)' },
    { code: 'SG', name: 'Singapore', id: 'c221', phoneCode: 'Singapore (+65)' },
    { code: 'SK', name: 'Slovakia', id: 'c222', phoneCode: 'Slovakia (+421)' },
    { code: 'SI', name: 'Slovenia', id: 'c223', phoneCode: 'Slovenia (+386)' },
    { code: 'SB', name: 'Solomon Islands', id: 'c224', phoneCode: 'Solomon Islands (+677)' },
    { code: 'SO', name: 'Somalia', id: 'c225', phoneCode: 'Somalia (+252)' },
    { code: 'ZA', name: 'South Africa', id: 'c226', phoneCode: 'South Africa (+27)' },
    { code: 'KR', name: 'South Korea', id: 'c227', phoneCode: 'South Korea (+82)' },
    { code: 'ES', name: 'Spain', id: 'c228', phoneCode: 'Spain (+34)' },
    { code: 'LK', name: 'Sri Lanka', id: 'c229', phoneCode: 'Sri Lanka (+94)' },
    { code: 'SD', name: 'Sudan', id: 'c230', phoneCode: 'Sudan (+249)' },
    { code: 'SR', name: 'Suriname', id: 'c231', phoneCode: 'Suriname (+597)' },
    { code: '', name: 'Svalbard and Jan Mayen', id: 'c232', phoneCode: 'Svalbard and Jan Mayen (+47)' },
    { code: 'SZ', name: 'Swaziland', id: 'c233', phoneCode: 'Swaziland (+268)' },
    { code: 'SE', name: 'Sweden', id: 'c234', phoneCode: 'Sweden (+46)' },
    { code: 'CH', name: 'Switzerland', id: 'c235', phoneCode: 'Switzerland (+41)' },
    { code: 'SY', name: 'Syria', id: 'c236', phoneCode: 'Syria (+963)' },
    { code: 'TW', name: 'Taiwan', id: 'c237', phoneCode: 'Taiwan (+886)' },
    { code: 'TJ', name: 'Tajikistan', id: 'c238', phoneCode: 'Tajikistan (+992)' },
    { code: 'TZ', name: 'Tanzania', id: 'c239', phoneCode: 'Tanzania (+255)' },
    { code: 'TH', name: 'Thailand', id: 'c240', phoneCode: 'Thailand (+66)' },
    { code: 'TG', name: 'Togo', id: 'c241', phoneCode: 'Togo (+228)' },
    { code: 'TK', name: 'Tokelau', id: 'c242', phoneCode: 'Tokelau (+690)' },
    { code: 'TO', name: 'Tonga', id: 'c243', phoneCode: 'Tonga (+676)' },
    { code: 'TT', name: 'Trinidad and Tobago', id: 'c244', phoneCode: 'Trinidad and Tobago (+1-868)' },
    { code: 'TN', name: 'Tunisia', id: 'c245', phoneCode: 'Tunisia (+216)' },
    { code: 'TR', name: 'Turkey', id: 'c246', phoneCode: 'Turkey (+90)' },
    { code: 'TM', name: 'Turkmenistan', id: 'c247', phoneCode: 'Turkmenistan (+993)' },
    { code: 'TC', name: 'Turks and Caicos Islands', id: 'c248', phoneCode: 'Turks and Caicos Islands (+1-649)' },
    { code: 'TV', name: 'Tuvalu', id: 'c249', phoneCode: 'Tuvalu (+688)' },
    { code: '', name: 'US. Virgin Islands', id: 'c250', phoneCode: 'US. Virgin Islands (+1-340)' },
    { code: 'UG', name: 'Uganda', id: 'c251', phoneCode: 'Uganda (+256)' },
    { code: 'UK', name: 'Ukraine', id: 'c252', phoneCode: 'Ukraine (+380)' },
    { code: 'AE', name: 'United Arab Emirates', id: 'c253', phoneCode: 'United Arab Emirates (+971)' },
    { code: 'GB', name: 'United Kingdom', id: 'c254', phoneCode: 'United Kingdom (+44)' },
    { code: 'US', name: 'United States', id: 'c255', phoneCode: 'United States (+1)' },
    { code: 'UY', name: 'Uruguay', id: 'c256', phoneCode: 'Uruguay (+598)' },
    { code: 'UZ', name: 'Uzbekistan', id: 'c257', phoneCode: 'Uzbekistan (+998)' },
    { code: 'VU', name: 'Vanuatu', id: 'c258', phoneCode: 'Vanuatu (+678)' },
    { code: '', name: 'Vatican', id: 'c259', phoneCode: 'Vatican (+379)' },
    { code: 'VE', name: 'Venezuela', id: 'c260', phoneCode: 'Venezuela (+58)' },
    { code: 'VN', name: 'Vietnam', id: 'c261', phoneCode: 'Vietnam (+84)' },
    { code: 'WF', name: 'Wallis and Futuna', id: 'c262', phoneCode: 'Wallis and Futuna (+681)' },
    { code: 'EH', name: 'Western Sahara', id: 'c263', phoneCode: 'Western Sahara (+212)' },
    { code: 'YE', name: 'Yemen', id: 'c264', phoneCode: 'Yemen (+967)' },
    { code: 'ZM', name: 'Zambia', id: 'c265', phoneCode: 'Zambia (+260)' },
    { code: 'ZW', name: 'Zimbabwe', id: 'c266', phoneCode: 'Zimbabwe (+263)' },
];
